apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nodejs
  labels:
    type: local
    app: nodejs
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi